// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Web.UI;

[Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = Constants.ApiFromAspNet)]
public enum HtmlTextWriterAttribute
{
    Accesskey,
    Align,
    Alt,
    Background,
    Bgcolor,
    Border,
    Bordercolor,
    Cellpadding,
    Cellspacing,
    Checked,
    Class,
    Cols,
    Colspan,
    Disabled,
    For,
    Height,
    Href,
    Id,
    Maxlength,
    Multiple,
    Name,
    Nowrap,
    Onchange,
    Onclick,
    ReadOnly,
    Rows,
    Rowspan,
    Rules,
    Selected,
    Size,
    Src,
    Style,
    Tabindex,
    Target,
    Title,
    Type,
    Valign,
    Value,
    Width,
    Wrap,
    Abbr,
    AutoComplete,
    Axis,
    Content,
    Coords,
    DesignerRegion,
    Dir,
    Headers,
    Longdesc,
    Rel,
    Scope,
    Shape,
    Usemap,
    VCardName,
}
