// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace System.Web.UI;

public enum HtmlTextWriterStyle
{
    BackgroundColor,
    BackgroundImage,
    BorderCollapse,
    BorderColor,
    BorderStyle,
    BorderWidth,
    Color,
    FontFamily,
    FontSize,
    FontStyle,
    FontWeight,
    Height,
    TextDecoration,
    Width,
    ListStyleImage,
    ListStyleType,
    Cursor,
    Direction,
    Display,
    Filter,
    FontVariant,
    Left,
    Margin,
    MarginBottom,
    MarginLeft,
    MarginRight,
    MarginTop,
    Overflow,
    OverflowX,
    OverflowY,
    Padding,
    PaddingBottom,
    PaddingLeft,
    PaddingRight,
    PaddingTop,
    Position,
    TextAlign,
    VerticalAlign,
    TextOverflow,
    Top,
    Visibility,
    WhiteSpace,
    ZIndex
}
