using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.AspNetCore.SystemWebAdapters.Analyzers;

/// <summary>
/// A source generator that generates dependency injection registration code for ASP.NET Framework including:
///
/// - ASP.NET MVC4
/// - ASP.NET Web API 2
///
/// We're using a source generator here to avoid taking hard dependencies on these frameworks or releasing separate
/// packages for each framework. The generated code will only be included in the compilation if the user is
/// referencing the relevant assemblies.
///
/// For each framework, we generate a new extension method `Add{Framework}DependencyInjection` that adds the relevant services
/// to the DI container.
///
/// We also generate a `AddSystemWebDependencyInjection` method that calls each of the individual framework methods for whatever
/// frameworks are referenced and will be automatically updated.
/// </summary>
[Generator]
public class FrameworkDependencyInjectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var options = context.AnalyzerConfigOptionsProvider
            .Select((c, _) =>
                c.GlobalOptions.TryGetValue("build_property.EnableSystemWebDependencyInjectionGenerator", out var enableSwitch) && enableSwitch.Equals("true", StringComparison.OrdinalIgnoreCase));

        var usedFrameworks = context.CompilationProvider.Select((compilation, token) => new FrameworksUsed
        {
            HttpApplicationHost = compilation.GetTypeByMetadataName("Microsoft.AspNetCore.SystemWebAdapters.Hosting.IDependencyRegistrar") is { },
            WebApi = compilation.GetTypeByMetadataName("System.Web.Http.Dependencies.IDependencyResolver") is { },
            Mvc = compilation.GetTypeByMetadataName("System.Web.Mvc.IDependencyResolver") is { },
        });

        context.RegisterSourceOutput(usedFrameworks.Combine(options), (context, combined) =>
        {
            var (frameworks, isEnabled) = combined;

            if (!isEnabled)
            {
                return;
            }

            // No need to do anything if they're not referencing SystemWebAdapters with the ASP.NET Framework hosting infrastructure
            if (!frameworks.HttpApplicationHost)
            {
                return;
            }

            var registrars = frameworks.GetRegistrars().ToList();
            var source = CreateSource(registrars);
            context.AddSource("DependencyInjectionServiceCollectionExtensions.g.cs", source);

            foreach (var registrarSource in registrars)
            {
                using var stream = typeof(FrameworkDependencyInjectionGenerator).Assembly
                    .GetManifestResourceStream($"Microsoft.AspNetCore.SystemWebAdapters.Analyzers.CSharp.Templates.{registrarSource.Name}.cs");

                if (stream is null)
                {
                    context.AddSource($"{registrarSource.Name}.g.cs", $"// Could not find resource for {registrarSource.Name}");
                }
                else
                {
                    context.AddSource($"{registrarSource.Name}.g.cs", SourceText.From(stream, canBeEmbedded: true));
                }
            }
        });
    }


    private sealed record class FrameworksUsed
    {
        public bool HttpApplicationHost { get; init; }

        public bool Mvc { get; init; }

        public bool WebApi { get; init; }

        public IEnumerable<DependencyRegistrar> GetRegistrars()
        {
            if (Mvc)
            {
                yield return new("Mvc", "System.Web.Mvc.DependencyResolver");
            }

            if (WebApi)
            {
                yield return new("WebApi", "System.Web.Http.GlobalConfiguration.Configuration.DependencyResolver");
            }
        }
    }

    private static string CreateSource(IReadOnlyCollection<DependencyRegistrar> registrars)
    {
        using var writer = new StringWriter();
        using var indentedWriter = new IndentedTextWriter(writer);

        indentedWriter.WriteLine("// <auto-generated />");
        indentedWriter.WriteLine();
        indentedWriter.WriteLine("using System;");
        indentedWriter.WriteLine("using System.Collections.Generic;");
        indentedWriter.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        indentedWriter.WriteLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        indentedWriter.WriteLine("using Microsoft.AspNetCore.SystemWebAdapters.Hosting;");
        indentedWriter.WriteLine();
        indentedWriter.WriteLine("namespace System.Web");
        indentedWriter.WriteLine("{");
        indentedWriter.Indent++;

        indentedWriter.WriteLine("internal static partial class SystemWebFrameworksDependencyInjectionServiceCollectionExtensions");
        indentedWriter.WriteLine("{");
        indentedWriter.Indent++;

        indentedWriter.WriteLine("/// <summary>");
        indentedWriter.WriteLine("/// Adds dependency injection support for ASP.NET Framework components including:");

        indentedWriter.WriteLine(@"/// <list type=""bullet"">");
        indentedWriter.Indent++;
        indentedWriter.WriteLine(@"/// <item>ASP.NET Framework Core Components: <see cref=""System.Web.HttpRuntime.WebObjectActivator"" /></item>");
        foreach (var registrar in registrars)
        {
            indentedWriter.WriteLine($@"/// <item>{registrar.Name}: <see cref=""{registrar.Api}"" /></item>");
        }
        indentedWriter.Indent--;
        indentedWriter.WriteLine("/// </list>");
        indentedWriter.WriteLine("/// </summary>");

        indentedWriter.WriteLine("public static void AddSystemWebDependencyInjection(this HttpApplicationHostBuilder builder)");
        indentedWriter.WriteLine("{");
        indentedWriter.Indent++;
        indentedWriter.WriteLine("builder.AddWebObjectActivator();");
        foreach (var registrar in registrars)
        {
            indentedWriter.WriteLine($"builder.Add{registrar.Name}DependencyInjection();");
        }
        indentedWriter.Indent--;
        indentedWriter.WriteLine("}");

        indentedWriter.Indent--;
        indentedWriter.WriteLine("}");
        indentedWriter.Indent--;
        indentedWriter.WriteLine("}");

        return writer.ToString();
    }

    private sealed record DependencyRegistrar(string Name, string Api);
}
